### PR TITLE
Add Dark Theme

### PR DESCRIPTION
**Pull request by ms10398**
Fixed https://github.com/fossasia/susi_chromebot/issues/63

Screenshots of the change-

Dark Theme-
susidark
Light Theme-
screenshot from 2017-09-27 22-31-41

@zamhaq @gabru-md 
I have implemented a basic two theme interface. 
There are some little bugs which I want to work upon to make it perfect.

### CODE REVIEW

**Comment by gabru-md** [comment]
awesome @ms10398
:+1:

**Comment by zamhaq** [comment]
@ms10398 nice work. Here is an issue when you switch themes and send messages :-
theme. You can create a new issue for this.
Thanks for the work. Much appreciated.

**Comment by gabru-md** [comment]
@zamhaq I will work on this issue.

**Comment by ms10398** [comment]
@gabru-md I would like to work on it after creating issue as I already started working on this issue.

**Comment by ms10398** [comment]
Yeah sure @gabru-md Go ahead
I will fix some other issues now

**Pull request merged**
