### PR TITLE
Update susi_chromebot.gif

### LINKED ISSUE #304: Update 'Working GIF' for susi extension
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/susi_server

**Current behavior:**

Current SUSI gif looks like this
https://github.com/fossasia/susi_chromebot/blob/master/susi_chromebot.gif

but since some layout of the chromebot has changed, it needs to be updated.
screenshot 115

**Expected behavior:**

screenshot 116

**Steps to reproduce:**

Just update the gif.

**Related code:**
NA
```
insert any relevant code here else remove this section
```
NA
**Other information:**

NA
**System information:**

NA
```
Your operating system
```
Linux
**Would you like to work on the issue?**

Please let us know if you can work on it or the issue should be assigned to someone else.
```
I would like to but someone with good gif recorder might be more helpful

### PR DESCRIPTION
**Pull request by prateekiiest**
Fixes #304 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [ ] The unit tests pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

- [ ] All the functions created/modified in this PR contain relevant docstrings.

#### Changes proposed in this pull request:

- Previously GIF was this https://github.com/fossasia/susi_chromebot#working-gif
- Now its this https://github.com/prateekiiest/susi_chromebot/tree/patch-1#working-gif

### CODE REVIEW

**Comment by prateekiiest** [comment]
reviews please

**Comment by prateekiiest** [comment]
Squashed it @stealthanthrax

**Comment by ms10398** [comment]
@gabru-md Have a look at it

**Comment by ms10398** [comment]
Thanks @prateekiiest @gabru-md @stealthanthrax

**Pull request merged**
