### PR TITLE
added descriptive logos in the susi navbar

### LINKED ISSUE #120: To add descriptive logos in susi navbar (UI/UX)
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/susi_server

Your operating system
MAC OS

**Would you like to work on the issue?**
 Yes, I would like to work on this issue

### PR DESCRIPTION
**Pull request by stealthanthrax**
31308512-8e413a12-ab95-11e7-864a-b02e48301724

This fixes #120 ,#118

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `nextgen` branch.
- [x] The unit tests pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

- [x] All the functions created/modified in this PR contain relevant docstrings.

#### Short description of what this resolves:
 UI update

#### Changes proposed in this pull request:
 Added descriptive logos in the susi-navbar

### CODE REVIEW

**Comment by stealthanthrax** [comment]
@zamhaq please check now

**Comment by zamhaq** [comment]
@stealthanthrax close the other PR you opened for the same issue. Thanks.

**Comment by stealthanthrax** [comment]
Done @zamhaq

**Comment by zamhaq** [comment]
@ms10398 @stealthanthrax @gabru-md please review.

**Comment by ms10398** [comment]
screenshot from 2017-10-10 22-57-09

There is a typo in the source attribute please do check it.

**Comment by stealthanthrax** [comment]
@ms10398 , i'll squash the commits afterwards ,can you check if the issue has been solved?

**Comment by ms10398** [comment]
@stealthanthrax Please resolve the conflicts

**Comment by stealthanthrax** [comment]
@zamhaq @ms10398  please check now

**Comment by zamhaq** [comment]
@ms10398 please review.

**Comment by ms10398** [comment]
Please Squash the commits @stealthanthrax

**Comment by stealthanthrax** [comment]
@ms10398: I have squashed the commits, please check now 😄

**Comment by stealthanthrax** [comment]
@ms10398 ,i have squashed the commits,please check now :smile:

**Comment by stealthanthrax** [comment]
@zamhaq

**Comment by stealthanthrax** [comment]
@zamhaq , i have tried my best to fix issue #118 too. 😄

**Comment by zamhaq** [comment]
@ms10398 @gabru-md please check if `microphone` can be allowed through the new window.

**Comment by ms10398** [comment]
@stealthanthrax I couldnt allow microphone what needs to be done now to allow the microphone

**Comment by zamhaq** [comment]
@ms10398 it should be the same process as before. When the new window opens, we should be able to allow microphone. I think the option won't appear if your microphone is already allowed.

**Comment by stealthanthrax** [comment]
@zamhaq @ms10398 any changes that I should make?

**Comment by zamhaq** [comment]
@stealthanthrax please squash your commits.

**Comment by stealthanthrax** [comment]
@zamhaq , I will be adding another PR for this issue tomorrow,as this PR is getting very sketchy

**Comment by stealthanthrax** [comment]
@zamhaq , i have made anew PR #155 ,please check it out

**Pull request closed without merging**
