### PR TITLE
UI improvements based on chat.susi.ai (Fixes #4)

### LINKED ISSUE #4: Incoroporate chat.susi.ai theme into susi_chromebot
Currently the susi_chromebot has a very basic look.
susi
It would be great if it looks something similar to https://chat.susi.ai/.
chatsusiai
The UI improvements would include the following changes :- 
1. Colors from chat.susi.ai
2. fonts similar to as used in chat.susi.ai
3. speech bubbles for sent messages.

Yes I would like to work on it.

### PR DESCRIPTION
**Pull request by zamhaq**
Fixes #4 
- [x] Colors from chat.susi.ai
- [x] fonts similar to as used in chat.susi.ai
- [x] speech bubbles for sent messages.
- [x] Fixed merge conflicts
please review @mariobehling 
susinewui

### CODE REVIEW

**Comment by gabru-md** [comment]
@zamhaq there is still a problem with your commits. It seems as if you're picking some other commits as well.
Kindly have a look

**Comment by gabru-md** [comment]
It would be great if you could "not merge" this before the SUSI API Integration. 
So that you can work upon the UI after PR #12 gets merged?

**Comment by zamhaq** [comment]
@gabru-md Do i need to have only a single commit in PR ?

**Comment by zamhaq** [comment]
@gabru-md @mariobehling Please take a look. I tried squashing the commits as best I could but somehow its been picking on @gabru-md and other commits. If its ok then please merge otherwise please help me resolve this.
Thanks.

**Comment by vaibhavsingh97** [comment]
@zamhaq I am seeing that you directly doing changes on your master fork. Please avoid doing this instead make new branch and then do whatever changes you want to. Then this situation will not appear.

**Pull request closed without merging**
