### PR TITLE
Fixed indentation and organised code by adding the css and js files i…

### LINKED ISSUE #208: Organise code and fix indendation
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/susi_server

**Current behavior:**
All the files are clustered now

**Expected behavior:**
To put all files in separate folder (diff folders for js and css folders)

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by stealthanthrax**
…n different folders

Fixes #208 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [x] The unit tests pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

- [x] All the functions created/modified in this PR contain relevant docstrings.

#### Changes proposed in this pull request:
Adds files in different  folders and fixes indentation in code to easy understanding of code

### CODE REVIEW

**Comment by ms10398** [comment]
Yeah it would be better to keep these little things as GCI task as it can be good for getting a start with project

**Comment by stealthanthrax** [comment]
@zamhaq , I left a comment on the previous PR.

**Comment by gabru-md** [comment]
@stealthanthrax It was discussed to be a part of GCI as a task.
I guess we will ave to wait for @zamhaq to comment something before me or @ms10398 can review

**Comment by stealthanthrax** [comment]
@gabru-md , I made a PR before it was discussed to be a part of GCI

**Comment by gabru-md** [comment]
Okay! if that is the case,
I will review it. But from now on, since GCI is going on, please refrain from taking up easy tasks that can be easily taken up by students and rather focus on making new and easy tasks for them to work on.

Advance and Difficult tasks can be worked upon by us.
@zamhaq @ms10398 comments?

**Comment by ms10398** [comment]
Agreed @gabru-md

**Pull request merged**
