### PR TITLE
added descriptive logos

### PR DESCRIPTION
**Pull request by stealthanthrax**
Fixes #

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `nextgen` branch.
- [x] The unit tests pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

- [x] All the functions created/modified in this PR contain relevant docstrings.

#### Short description of what this resolves:
upload

### CODE REVIEW

**Comment by stealthanthrax** [comment]
@zamhaq @ms10398 ,please have a look

**Comment by gabru-md** [comment]
@stealthanthrax wouldn't it be better if you could use something like material icons rather than heavy images ?
I'm just proposing the changes. But we can wait till @zamhaq comments.

**Comment by zamhaq** [comment]
@gabru-md its ok, you people can keep reviewing and the approving PR's. Maybe @mariobehling will then merge those PR. Cheers. ☺️

**Comment by ms10398** [comment]
I agree it would be better if we could use material icons or some similar icon package.

**Comment by stealthanthrax** [comment]
@gabru-md @ms10398 , to match the icons present in the main susi bot,i have made the photo's on photoshop,but if you guys can suggest a link to the icons package ,I will be happy to change it.

**Comment by ms10398** [comment]
What do you say @gabru-md file size is small and as the icons are small and used in extension they are okay
But @stealthanthrax try to use material icons or icon packs from next time.

**Comment by stealthanthrax** [comment]
@ms10398 , agreed .

**Pull request merged**
