### PR TITLE
Add Susi Chat, Susi Skills shortcut in Option menu #343

### LINKED ISSUE #343: Add Susi Chat, Susi Skills shortcut in Option menu
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/susi_server

**Current behavior:**
Currently not present

**Expected behavior:**
Add shortcut in options to go to https://chat.susi.ai/ and https://skills.susi.ai/ from right click the app

**Steps to reproduce:**
Right click on susi extension logo 

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by fragm3**
Fixes #343

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [x] The unit tests pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

- [x] All the functions created/modified in this PR contain relevant docstrings.

#### Short description of what this resolves:

Option to go to https://chat.susi.ai , https://skills.susi.ai

####Screenshot

screen shot 2018-09-24 at 6 12 11 pm

#### Changes proposed in this pull request:

- Created context menu
- Context event listener to open a new tab in chrome

### CODE REVIEW

**Comment by rupav** [comment]
@fragm3 can you please share some screenshots?

**Comment by gabru-md** [comment]
@fragm3 please add some screenshot and fill the PR template indicating the issue number that this PR is solving. Thank you :)

**Comment by fragm3** [comment]
Screenshot:
screen shot 2018-09-24 at 6 12 11 pm

**Comment by fragm3** [comment]
@gabru-md done

**Comment by gabru-md** [comment]
@rupav a review would be great. since I need 2 reviews to merge PRs with substantial work :D

**Pull request merged**
