### PR TITLE
UI Improvement: Scrollbar Redesigned

### PR DESCRIPTION
**Pull request by vatz88**
Scrollbar Redesigned

**Before**

old
old_dark

**Now**

new
new_dark

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `nextgen` branch.
- [x] The unit tests pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

- [x] All the functions created/modified in this PR contain relevant docstrings.

#### Short description of what this resolves:

Improved UI

#### Changes proposed in this pull request:

Scrollbar is now

- thinner and beautiful
- color is according to the theme

### CODE REVIEW

**Comment by vatz88** [comment]
@zamhaq there is a CSS property `width` currently set to `3px`. It can be increased to make it little more thicker. I personally like it slim. And yes for thicker scrollbar rounded border would look better.

I'll add another commit if you want it thicker.

**Comment by zamhaq** [comment]
@vatz88 yeah, make to `5px` and corners rounded. Thanks.

**Comment by vatz88** [comment]
@zamhaq increased scrollbar `width` to 10px. Rounded corners were hardly noticeable in `5px` width.

**Comment by zamhaq** [comment]
@vatz88 please squash the commits.

**Comment by vatz88** [comment]
@zamhaq I didn't get you. GitHub does give on option for Squash and merge on PR right?

**Comment by zamhaq** [comment]
@vatz88 yes. But in fossasia, the contributors should squash the commits in their `PR`.

**Comment by vatz88** [comment]
Ah ok I'll do it :+1:

**Pull request merged**
