### PR TITLE
add icon in the extensions management page (chrome://extensions).

### LINKED ISSUE #92: Add different icon sizes in manifest.json
This is to ensure susi.ai icon'size on the toolbar is compatible with the platform used.
I had done similar type in fossasia/susi_firefoxbot [https://github.com/fossasia/susi_firefoxbot/pull/22](url) where I used an svg icon.
But Chrome does not show svg icon so will do something else.
Also, recommended sizes are:
[https://developer.chrome.com/apps/manifest/icons](url) .

**Would you like to work on it?**
Yes.

### PR DESCRIPTION
**Pull request by rupav**
fixes #92
added icons property, previous icon enlarges itself to 48x48:
Earlier

Change propsed:

### CODE REVIEW

**Comment by rupav** [comment]
@gabru-md  does the work as suggested in  #92

**Comment by zamhaq** [comment]
@rupav Please mention the issue number in your pull request comment.

**Comment by rupav** [comment]
@zamhaq  @gabru-md  I have changed 'icon.png' to 'images/icon.ong' as all images are moved on to the folder 'images'.

**Comment by ms10398** [comment]
Solve the merge conflicts and squash your commits @rupav

**Comment by rupav** [comment]
Hi @ms10398, I dont know how to resolve conflicts.

**Comment by rupav** [comment]
@zamhaq  @ms10398  Please merge now, I somehow resolved the conflict :)

**Comment by rupav** [comment]
Also I followed this;
git rebase -i HEAD~3
for squashing, but it didnt help, thats why its showin 2 commits

**Comment by gabru-md** [comment]
@rupav i see that you used web gui for making the change.
I say that you re-sync again with main repo
And make the changes then send the PR.
Meanwhile close this one.

**Comment by rupav** [comment]
ok, resyncing. Sending new PR

**Pull request closed without merging**
