### PR TITLE
add compose message functions

### LINKED ISSUE #46: Reduce redundancy in code
Currently there is too much redundancy in creating new messages. I will put them into separate methods so that redundancy is reduced.

Yes I will work on this.

### PR DESCRIPTION
**Pull request by zamhaq**
Fixes #46 
Added functions for composing message

### CODE REVIEW

**Comment by zamhaq** [comment]
@gabru-md @ms10398 Please review.

**Comment by gabru-md** [comment]
@zamhaq it is great! 
We must follow this process. What we can do from now onwards is

- make changes
- rectify mistakes
- finally make seperate functions.

This will help us and the contributirs to understand the code. 
Thanks!

**Comment by zamhaq** [comment]
@gabru-md Yes. Please add a line to `contributing.md` saying `make code as modular as possible`.

**Comment by gabru-md** [comment]
Will be sending a PR soon

**Pull request merged**
