### PR TITLE
Fixes #159 : Change color of micmodal in dark mode

### LINKED ISSUE #159: Speak now doesnt follows dark theme in the mode
**I'm submitting a ...** 
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/susi_server

**Current behavior:**
When we click on voice input button in dark mode the speak now container doesnt follows dark theme 

**Expected behavior:**
It should follow the dark theme in dark mode

**Steps to reproduce:**
In dark mode click on voice input button

**Screenshot**
screenshot from 2017-10-25 13-46-42

**System information:**
`Ubuntu 17.04`

**Would you like to work on the issue?**
`Yes`

### PR DESCRIPTION
**Pull request by akshatnitd**
Fixes #159 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [x] The unit tests pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

- [x] All the functions created/modified in this PR contain relevant docstrings.

#### Short description of what this resolves:
The background color of the Mic Modal doesn't change in accordance to dark theme.

#### Changes proposed in this pull request:

- Changed the background color of mic modal in dark theme.
- Changed the mic animate gif to a better looking one, similar to the one present in chat.susi.ai

### CODE REVIEW

**Comment by akshatnitd** [comment]
@gabru-md Please review :)

**Comment by akshatnitd** [comment]
@ms10398 Done :+1:

**Comment by ms10398** [comment]
@gabru-md What do you think about the color sequence of it. Do you like the color sequence or should we change it.

**Comment by akshatnitd** [comment]
@zamhaq Here are the other 2 possible colors.



imageedit_4_8025498900

**Comment by zamhaq** [comment]
@akshatnitd I think the second one is more in line with the other element colors and would be better if you make the speak now text lighter. What do you think?

**Comment by ms10398** [comment]
Yeah i agree with you @zamhaq

**Comment by akshatnitd** [comment]
@zamhaq Yes, correct. Will make the changes and update the PR :+1:

**Comment by akshatnitd** [comment]
@zamhaq @ms10398 Updated the PR comment with the updated screenshot

**Pull request merged**
