### PR TITLE
added the descriptive logos in front of the li tags in dropdown menu(UI/UX)

### PR DESCRIPTION
**Pull request by stealthanthrax**
#### Checklist

- [x ] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [ x] My branch is up-to-date with the Upstream `nextgen` branch.
- [ x] The unit tests pass locally with my changes 
- [x ] I have added tests that prove my fix is effective or that my feature works
- [ x] I have added necessary documentation (if appropriate)

- [x ] All the functions created/modified in this PR contain relevant docstrings.

#### Short description of what this resolves:

Matches the main susi chatbot

#### Changes proposed in this pull request:

-screen shot 2017-10-07 at 7 26 33 pm

### CODE REVIEW

**Comment by zamhaq** [comment]
@stealthanthrax squash your commits. What issue is this fixing? The drop-down shrinks and enlarges when hovering on the different links.

**Comment by stealthanthrax** [comment]
@zamhaq , the issue i am facing for the squash is that i am seeing these commits in the log but am unable to see these commits in when i am trying to rebase these commits .Could you please help me   ?

**Comment by stealthanthrax** [comment]
@zamhaq ,also since this is only a UI update ,so , do i need to create an issue for this?

**Comment by zamhaq** [comment]
@stealthanthrax yes create an issue. Actually, you could have made these changes in the previous `PR` you sent #108 since its a very small part of that. Making multiple small PR's for related changes is not very effective and having no issues blocks other contributors from working on it.

**Comment by stealthanthrax** [comment]
Closed

**Pull request closed without merging**
