### PR TITLE
Refactor Show Password UI and logged in message.

### LINKED ISSUE #318: 'Show password' filed should not be editable i.e. input type.
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/susi_server

**Current behavior:**

Currently we can edit the Show password field.
**Expected behavior:**

It should not be editable.
**Steps to reproduce:**

Go to login page, and check show password. then try to edit it.
**Related code:**

**Would you like to work on the issue?**
Yes.

### PR DESCRIPTION
**Pull request by rupav**
Fixes #318  #317 #320 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [x] The unit tests pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

- [ ] All the functions created/modified in this PR contain relevant docstrings.

#### Short description of what this resolves:
Now Show password filed is non-editable by adding 'disabled' attribute. And use `keyup` event instead of `keypress` to register even the last character types in password field.

### CODE REVIEW

**Comment by rupav** [comment]
Reference: https://stackoverflow.com/questions/30668236/keypress-event-not-working-with-the-last-inserted-character
@zamhaq @gabru-md instead of having a different filed, we can show the password in the same filed as 'Password'. Let me know if that will be good.

**Comment by stealthanthrax** [comment]
@rupav , please check the codacy logs

**Comment by rupav** [comment]
@stealthanthrax made the required changes. Please review.

**Comment by rupav** [comment]
Reopened 👍

**Comment by Ananthavijay** [comment]
@rupav I think its better to remove show password field 😄

**Comment by Ananthavijay** [comment]
@rupav I think it's better to remove show password field 😄

**Comment by rupav** [comment]
Removed it in my 3rd commit @Ananthavijay 😃

**Comment by rupav** [comment]
@gabru-md working on it 👍

**Comment by rupav** [comment]
Done @gabru-md . Since we are using bootstrap 4, haven't found much of resource on how to put custom icon inside input field. Only able to put alongside the password field.
Added script to include fontawesome.
image

**Comment by Ananthavijay** [comment]
@rupav If the eye button comes inside with a box will look good I think

**Comment by rupav** [comment]
Agreed, but custom feedback input icons in bootstrap 4 doesn't have much in official documentation. Thats why asked @gabru-md for the same. Refer my last comment in this thread.

**Comment by rupav** [comment]
Resolved merge conflicts. 😃.

**Comment by gabru-md** [comment]
Solves multiple issues. Thanks @rupav

**Pull request merged**
