### PR TITLE
Changed permissions

### LINKED ISSUE #183: Fix permissions
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/susi_server

**Current behavior:**
The extension has the permission to `Read and change all the data on the websites that you visit`.

**Expected behavior:**
Check if its possible to require fewer permissions and still be fully functional.
path939

**Steps to reproduce:**
Check details on extensions page.

**Related code:**
check `manifest.json` `permission` field.

**Would you like to work on the issue?**
No.

### PR DESCRIPTION
**Pull request by ms10398**
Fixes #183 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [x] The unit tests pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)
- [x] All the functions created/modified in this PR contain relevant docstrings.

#### Short description of what this resolves:
Changed the permissions to fewer.

#### Screenshot
permission

@zamhaq @gabru-md @stealthanthrax Have a look These are the least required permissions to run the project.

### CODE REVIEW

**Comment by ms10398** [comment]
I am not sure @zamhaq but i tried to reduce the permissions to the least required.

**Comment by ms10398** [comment]
Welcome!! :smile:

**Comment by stealthanthrax** [comment]
@zamhaq @ms10398 , I think that removing the ajax permissions will have an effect on the login feature?

**Comment by ms10398** [comment]
I changed the permissions according to now as you add the login feature you can add its permissions with it in manifest.json file.
What do you think @stealthanthrax

**Comment by zamhaq** [comment]
@stealthanthrax The extension was still making ajaz requests to get answers, have you tested it yet?

**Comment by stealthanthrax** [comment]
@zamhaq , i agree that the ajax was still making requests.But I believe that documenting every permission will make it more systematic.Rest, is a unanimous call. 👍

**Comment by zamhaq** [comment]
@stealthanthrax if ajax still works, it might be because it does not require special permissions. I think the extensions would block access anything for which permissions is not specified. Anyways, you can test it on login later.

**Pull request merged**
