### PR TITLE
Added the option of predefined themes

### LINKED ISSUE #197: To add a selection of predefined colored themes as in the web app
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/susi_server

**Current behavior:**
Only light and dark themes are available 

**Expected behavior:**
More than two choices for default themes

**Would you like to work on the issue?**

Yes, I would like to work on this issue.

### PR DESCRIPTION
**Pull request by stealthanthrax**
Fixes #197 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [x] The unit tests pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

- [x] All the functions created/modified in this PR contain relevant docstrings.

#### Short description of what this resolves:
More than two choices added for default themes and minor style changes in ui of settings page

#### Changes proposed in this pull request:
Added the custom themes in settings page

### CODE REVIEW

**Comment by stealthanthrax** [comment]
screen shot 2017-12-06 at 12 40 57 am
@zamhaq @gabru-md @ms10398 ,please have a look

**Comment by stealthanthrax** [comment]
@gabru-md , take a look

**Comment by gabru-md** [comment]
@stealthanthrax this looks more elegant and good.
Great Work!

**Comment by stealthanthrax** [comment]
Thanks @gabru-md 😄

**Comment by stealthanthrax** [comment]
@zamhaq , have a look now 😄

**Pull request merged**
