### PR TITLE
Fix Dark Theme Error

### PR DESCRIPTION
**Pull request by ms10398**
Fixes https://github.com/fossasia/susi_chromebot/issues/75

#### Checklist

- [X] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [X] My branch is up-to-date with the Upstream `master` branch.
- [ ] The unit tests pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] I have added necessary documentation (if appropriate)
- [X] All the functions created/modified in this PR contain relevant docstrings.

#### Short description of what this resolves:

It fixes the dark theme errors which were there.

#### Changes proposed in this pull request:

- Full Compatibility for Dark Theme
Sorry for the delay @zamhaq @gabru-md

### CODE REVIEW

**Comment by zamhaq** [comment]
@ms10398 the side arrows on the chat bubbles remain the same colour when the theme is changed. Please make their colour change as well.

**Comment by ms10398** [comment]
@zamhaq @gabru-md Review it

**Comment by zamhaq** [comment]
@ms10398 ask for reviews in the gitter channel too. Most of our reviews are only limited to us.

**Comment by mariobehling** [comment]
Cheers. Please work with the community to get more reviews for your PRs. Thanks.

**Pull request merged**
