### PR TITLE
Fixing UI & UX

### PR DESCRIPTION
**Pull request by niteshkumarniranjan**
Fixes #

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [x] The unit tests pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

- [ ] All the functions created/modified in this PR contain relevant docstrings.

#### Short description of what this resolves:
screenshot 59
1.Fixed Menu item design.
2.Fixed TextBox to fill the space.
3.Removes Textbox resize corner for UI Improvements.

### CODE REVIEW

**Comment by niteshkumarniranjan** [comment]
@zamhaq Done!

**Comment by sayak119** [comment]
@niteshkumarniranjan Please squash your commits into one.

**Comment by niteshkumarniranjan** [comment]
@sayak119 Done!

**Comment by niteshkumarniranjan** [comment]
@zamhaq I just messed up with my work while resolving conflict so it took me time because I haven't resolved any conflict yet. now it's fine.

**Comment by niteshkumarniranjan** [comment]
Sure!
screenshot 86

**Comment by niteshkumarniranjan** [comment]
@stealthanthrax Done!

**Comment by niteshkumarniranjan** [comment]
@zamhaq Why didn't merged this PR.

**Comment by zamhaq** [comment]
Standard procedure: 3rd reviewer merges PR, but since I am the only maintainer here, if no one else reviews till tomorrow, I will merge it. 😀

**Comment by niteshkumarniranjan** [comment]
Thanks!

**Pull request merged**
