### PR TITLE
SUSI AI Integrated into ChromeBot

### PR DESCRIPTION
**Pull request by gabru-md**
Integrated SUSI AI into SUSI_CHROMEBOT so that the answers can be fetched from SUI itself.
A further Enhancement is also done in this case. If SUSI returns a link and image then proper
formatting is done to print the image with relevant link.

Fixes https://github.com/fossasia/susi_chromebot/issues/5

PS : @hpdang @zamhaq

### CODE REVIEW

**Comment by gabru-md** [comment]
Screen-Shots of the changes.

Working Chat with SUSI: 
scs

Image and Link Search with SUSI:
emsscs

**Comment by zamhaq** [comment]
@gabru-md Did you try to chat with susi through the popup ? It works when open `popup.html` in browser but if you try through the `extension popup` it  wont work. You should checkout `chrome api docs`.
:+1:

**Comment by gabru-md** [comment]
I've created another issue for manifest.json and will be working on it now.
@zamhaq 
So i believe that this PR can be merged and i can then work upon adding permissions to manifest.json
Kindly merge it.
Cheer!

**Comment by zamhaq** [comment]
@gabru-md Please request with others for reviews too. Once two reviews are done, we can merge it.
Thanks.

**Comment by zamhaq** [comment]
@gabru-md Please let https://github.com/fossasia/susi_chromebot/pull/16 this merge first as this might break the current css. 
Thanks.
Meanwhile you can keep working on fixing the permissions.
@mariobehling what do you say ?

**Pull request closed without merging**
