### PR TITLE
Fixes #272 Add Hound CI

### LINKED ISSUE #272: Add Hound CI
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [x] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/susi_server

**Current behavior:**

Currently, Hound CI is not present in the repo.
**Expected behavior:**

Adding houndCI in the repo, will help us to review the code for the violation of code styling.
**Steps to reproduce:**

**Related code:**

```
insert any relevant code here else remove this section
```

**Other information:**

**System information:**

```
Your operating system
```

**Would you like to work on the issue?**

Yes, I wanna work on this.
```

### PR DESCRIPTION
**Pull request by bhaveshAn**
Fixes #272 

#### Checklist

- [ ] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [ ] The unit tests pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

- [x] All the functions created/modified in this PR contain relevant docstrings.

#### Short description of what this resolves:

Added Hound CI
#### Changes proposed in this pull request:

@ms10398 @zamhaq @mariobehling Please review

### CODE REVIEW

**Comment by gabru-md** [comment]
I agree with @stealthanthrax

**Comment by bhaveshAn** [comment]
@stealthanthrax @gabru-md 
Please check this https://github.com/fossasia/susi_chromebot/blob/master/.travis.yml
```
language: node_js
node_js:
- "6"
```
Here, you will find that the Travis is not running any script (so not doing anything) and not even checking the codestyling (which is done by hound in this PR), and thats the reason we haven't received any pull request till date in this repo where the build has failed.

Even you can check the Travis logs https://travis-ci.org/fossasia/susi_chromebot/builds/329159169?utm_source=github_status&utm_medium=notification

And Codacy, checks the code quality and not Code styling (ex. JSHINT in JavaScript and FLAKE8 in Python)

**Comment by ms10398** [comment]
We are using JSHINT in the code
And yes builds have failed in it but we just improve.

**Comment by bhaveshAn** [comment]
> We are using JSHINT in the code
And yes builds have failed in it but we just improve

Where since script to run jshint is not present in `.travis.yml`

**Comment by ms10398** [comment]
https://travis-ci.org/fossasia/susi_chromebot

https://github.com/fossasia/susi_chromebot/pull/279

I failed build intentionally check if its running or not

Yeah its `grunt` magic made by me!!

**Comment by zamhaq** [comment]
@ms10398 @bhaveshAn can be closed?

**Comment by ms10398** [comment]
Yes

**Pull request closed without merging**
