### PR TITLE
Fixes #118: Open settings page in a separate window

### LINKED ISSUE #118: Opening the settings tab in a new window.
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/susi_server

**Current behavior:**
Settings tab opens in a new tab which makes the user to ultimately leave his work which ultimately destroys the purpose of making a chromebot

**Expected behavior:**
To make the window open in a new window of custom size.

Your operating system
Mac OS

**Would you like to work on the issue?**

Yes , would like to work on this issue.

### PR DESCRIPTION
**Pull request by akshatnitd**
Fixes #118 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [ ] The unit tests pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

- [x] All the functions created/modified in this PR contain relevant docstrings.

#### Short description of what this resolves:
Open settings page in a separate window rather than a new tab

#### Changes proposed in this pull request:

- Open settings page in a separate window of custom size of 800x800

### CODE REVIEW

**Comment by akshatnitd** [comment]
@mariobehling @zamhaq @ms10398 Please review :)

**Comment by gabru-md** [comment]
Thanks @akshatnitd.
LGTM 
@zamhaq please review

**Comment by zamhaq** [comment]
@ms10398 @gabru-md Were you guys able to see any popups for allowing microphone when opening settings in the new window?

**Comment by ms10398** [comment]
Yes @zamhaq 

screenshot from 2017-10-23 12-51-51

**Comment by zamhaq** [comment]
@ms10398 where did you find the popup for allowing microphone?

**Comment by ms10398** [comment]
In the dropdown when we click on the settings option @zamhaq

**Comment by zamhaq** [comment]
micpop

@ms10398 do you see that small popup? that asks for permissions of microphone, in this case, the new window that opens does not have any such popups. Please try blocking your microphone access for susi with old setup(from the tab that opens), and then checkout with this window popup, see if there is any way to allow the microphone then. Thanks.

**Comment by ms10398** [comment]
I tried it @zamhaq Yes the popup is not there but the microphone is allowed and works but there should be a popup asked to allow or not to allow.
When i opened it first time for checking there was a popup but not this time I dont know why.

**Comment by akshatnitd** [comment]
@ms10398 The pop-up will show until anyone option among Allow and Block is not selected. Once, it is selected, it won't show up. To trigger the popup again, you need to remove the *susi_ai* from [here](chrome://settings/content/microphone).

Also, I have updated the PR after rebasing with master.

**Comment by ms10398** [comment]
From where @akshatnitd ?

**Comment by zamhaq** [comment]
@akshatnitd @ms10398 ok then, I don't know why the popup did not appear for me, I did remove the extension first.

**Comment by akshatnitd** [comment]
@ms10398  From this link **chrome://settings/content/microphone**

**Comment by ms10398** [comment]
Thanks it works now perfectly

**Pull request merged**
