### PR TITLE
Fixes #223 :Improve the UI and UX of login page

### LINKED ISSUE #223: Improve the UI of the settings page
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/susi_server

**Current behavior:**
The buttons are not aligned properly and UX of settings page is poor.

**Expected behavior:**
Buttons should be aligned properly and UI, UX of page should be improved.

**Steps to reproduce:**
Go to the settings page of the chromebot

**System information:**

```
Arch Linux
```
**Screenshot?**
screenshot from 2017-12-16 01-43-31

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by akshatnitd**
Fixes #223

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [x] The unit tests pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

- [x] All the functions created/modified in this PR contain relevant docstrings.

#### Short description of what this resolves:
The UI of the login page was not clean and there were some UX issues as well.

#### Changes proposed in this pull request:

- Improved the UI and UX of settings page.
- Refactored the related code 

**Screenshots**
deepinscreenshot_select-area_20171216030502
screenshot from 2017-12-16 03-05-50

### CODE REVIEW

**Comment by akshatnitd** [comment]
@ms10398 @zamhaq @gabru-md Please review :)

**Comment by akshatnitd** [comment]
@stealthanthrax I had tried it, but the buttons weren't visible.
Here is a screenshot. I can still change the colors if required.

screenshot from 2017-12-16 10-47-06

**Comment by gabru-md** [comment]
@akshatnitd The green one looks better though!

**Comment by akshatnitd** [comment]
@gabru-md Yes, exactly :smile:

**Comment by ms10398** [comment]
Yeah the green looks better
@zamhaq Whats your view

**Comment by zamhaq** [comment]
@ms10398 blue is not visible much. Please approve if it is ok.

**Pull request merged**
