### PR TITLE
 fixes #417 : link to Settings.html in the drop-down menu added . 

### LINKED ISSUE #417: Addings Settings Link Inside Drop Down Menu
**I'm submitting a ...**  (check one with "x")
- [x] feature request

**Current behavior:**

There is no link to Settings.html in the drop-down menu in chrome bot.

screenshot from 2018-10-05 16-05-27

**Would you like to work on the issue?**

Please let us know if you can work on it or the issue should be assigned to someone else.
```
Yes

### PR DESCRIPTION
**Pull request by tathagat2006**
Fixes #417 

#### Checklist

- [ yes] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [ yes] My branch is up-to-date with the Upstream `master` branch.
- [ yes] The unit tests pass locally with my changes 
- [yes ] I have added tests that prove my fix is effective or that my feature works
- [yes ] I have added necessary documentation (if appropriate)

- [ yes] All the functions created/modified in this PR contain relevant docstrings.

#### Short description of what this resolves:
 link to Settings.html in the drop-down menu added . 
image

#### Changes proposed in this pull request:
Pop up window contains settings button to navigate to seetings.html
-
-
-

### CODE REVIEW

**Comment by sk9331657** [comment]
Already present in #418

**Comment by gabru-md** [comment]
I suppose we can merge this stuff, logout/login should be the last button in the drop down, isn't it? @rupav @ms10398 @anshumanv ?

**Comment by sk9331657** [comment]
@gabru-md Yes , It can be merged.

**Comment by sk9331657** [comment]
@gabru-md   The patch has been already submitted in #418

**Comment by rupav** [comment]
@tathagat2006 duplicate PR, so this can be closed. Refer #420 . @gabru-md commented the need to have settings option above Login/Logout option in the dropdown in that PR.

**Comment by tathagat2006** [comment]
@gabru-md .idea folder removed. Thanks :)

**Comment by sk9331657** [comment]
@tathagat2006  This is copy of  #418

**Comment by akshatnitd** [comment]
The fix for this issue has already been merged, You can try out some other issues.

**Pull request closed without merging**
