### PR TITLE
Fix UI bug

### LINKED ISSUE #6: fixing UI bug
This is basically small bug regarding size of input text by increasing its size.

**Would you want to work on this issue?**
Yes

### PR DESCRIPTION
**Pull request by S2606**
Fixes #6

### CODE REVIEW

**Comment by zamhaq** [comment]
@S2606 Please add some screenshots. Thanks.

**Comment by S2606** [comment]
image

**Comment by gabru-md** [comment]
:+1:

**Comment by zamhaq** [comment]
@S2606 Your issue and the PR is really unclear. Please update issue with **Actual Behaviour** and **Expected Behaviour**. As far as the PR is concerned, you have only increased the number of columns.
Please update and resolve conflicts. Thanks.

**Pull request closed without merging**
