### PR TITLE
Revert "Directs to susi homepage when clicked on the header image"

### PR DESCRIPTION
**Pull request by zamhaq**
Reverts fossasia/susi_chromebot#37

### CODE REVIEW

**Comment by gabru-md** [comment]
@zamhaq Why reverting this?

**Comment by zamhaq** [comment]
@gabru-md does not work. I didn't check the `PR` before merging since @ms10398 approved it.
Please @gabru-md @ms10398 check the `PR` before approving (if you are not doing so already).

**Comment by ms10398** [comment]
Yes i checked again
And this does not works

**Comment by zamhaq** [comment]
@gabru-md @ms10398 since we don't have automatic tests yet, Please fetch the `PR` locally before **approving**.
Thanks.

**Comment by gabru-md** [comment]
@zamhaq I did not approve that one.
otherwise would have checked.

**Comment by ms10398** [comment]
Sorry for inconvenience caused @zamhaq

**Comment by zamhaq** [comment]
@gabru-md I know. I am just giving a reminder. It was a mistake on my part too. Anyways, it happens. @ms10398 no problem.  😄

**Comment by ms10398** [comment]
I checked it as a HTML page forgot to check it in extension it works as a HTML page. I will fix this issue and make a PR 
@zamhaq Please review https://github.com/fossasia/susi_chromebot/pull/43 https://github.com/fossasia/susi_chromebot/pull/41

**Comment by gabru-md** [comment]
@ms10398 If you have not started working on it then i will send a PR straight away, as i have the fix !

**Comment by ms10398** [comment]
@gabru-md made the fix too
But go ahead and add it to your PR so that we need not to make another PR for it

**Pull request merged**
