### PR TITLE
Adds Toggle to Login Button and to the Login Page

### PR DESCRIPTION
**Pull request by gabru-md**
When a user if logged in the page changes to Logout and the dropdown
changes to Logout as well with the svg change as well.

Closes https://github.com/fossasia/susi_chromebot/issues/247

Fixes #

#### Checklist

- [ ] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [ ] My branch is up-to-date with the Upstream `master` branch.
- [ ] The unit tests pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

- [ ] All the functions created/modified in this PR contain relevant docstrings.

#### Changes proposed in this pull request:

-
-
-

### CODE REVIEW

**Comment by gabru-md** [comment]
@ms10398 I was out for some work. Will do it asap :)

**Comment by gabru-md** [comment]
@ms10398 @zamhaq Review and merge. 
All the errors have been resolved :)

**Comment by gabru-md** [comment]
Done @zamhaq @ms10398

**Comment by zamhaq** [comment]
@ms10398 please approve if alright.

**Comment by gabru-md** [comment]
@zamhaq merge?

**Pull request merged**
