### PR TITLE
Susi now has a female voice

### LINKED ISSUE #202: The UI Should be more Agile!
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/susi_server

**Current behavior:**
feature
feature1

**Expected behavior:**

It will hold the setting more a little longer to avoid the above situation! :sweat_smile: 

**Steps to reproduce:**

Hover to the vertical-3-dots, which is used to view the options.

**Other information:**

**System information:**

```
Your operating system : Windows
```

**Would you like to work on the issue?**

Not right now. :wink:

### PR DESCRIPTION
**Pull request by arnav-mandal1234**
Fixes  #202 #193 #261  

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [x] The unit tests pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)
- [x] All the functions created/modified in this PR contain relevant docstrings.

#### Short description of what this resolves:
* Susi now has a female voice. (#193 )
* UI made agiler (#202 )
* console error fixed (#261 )

  aaa
no error
male female

### CODE REVIEW

**Comment by arnav-mandal1234** [comment]
@mariobehling @ms10398 @zamhaq kindly look into this.

**Comment by zamhaq** [comment]
@arnav-mandal1234 did you meant male-voice? :confused: if so please change title of the PR :smile:

**Comment by arnav-mandal1234** [comment]
@zamhaq susi already had a male voice.

**Comment by stealthanthrax** [comment]
@arnav-mandal1234 , voice no. 21 or 27 goes well with female accent. You try using them.

**Comment by arnav-mandal1234** [comment]
@zamhaq @stealthanthrax on my laptop the male voice was same as the previous one and I added the female voice there. And the array length of voices is 21, So, I can't choose those voices 21/27.What is the issue I am facing?

**Comment by zamhaq** [comment]
@arnav-mandal1234 sorry, I haven't explored this issue much, cannot suggest anything :slightly_smiling_face: @stealthanthrax might help?

**Comment by stealthanthrax** [comment]
^the above approval was a mistake

**Comment by arnav-mandal1234** [comment]
@ms10398 @zamhaq @stealthanthrax @gabru-md Kindly look into this. I have made the changes as suggested.

**Pull request merged**
