### PR TITLE
Add minimum password limit for the user

### LINKED ISSUE #326: Add atleast 6 characters limit/check as per susi ai for password setting and change.
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/susi_server

**Current behavior:**

Currently while signing up, entering password with less than 6 characters, gives an alert of `Sign up failed. Try again`. Similarly, no error shows up while filling up `Change Password` field.

**Expected behavior:**

susi_chromebot should indicate atleast 6 character limit.

**Steps to reproduce:**

Try filling Signup or changing password when logged in by entering password less than 6 characters.

**Would you like to work on the issue?**
Yes.

### PR DESCRIPTION
**Pull request by rupav**
Fixes #326 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [x] The unit tests pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

- [x] All the functions created/modified in this PR contain relevant docstrings.

#### Short description of what this resolves:
it gives a user info about `minimum password limit of 6`, both at setting up new password (at signup) and changing password (in change password form). Help text gets removed, if user enters characters greater than 5.

#### Changes proposed in this pull request:

- Color of warning/infp text is set to white, as `red` is not showing up clearly on a blue background.
- Text is centered.

image
image

### CODE REVIEW

**Comment by rupav** [comment]
@zamhaq @stealthanthrax @gabru-md please review.

**Comment by ms10398** [comment]
Great @rupav

**Comment by rupav** [comment]
Made the changes, submit button disabled until atleast 6 characters are entered in password field.
image

**Comment by rupav** [comment]
@gabru-md @ms10398 @zamhaq now you can review.

**Comment by rupav** [comment]
Please review @stealthanthrax

**Pull request merged**
