### PR TITLE
Changed Button format to Anchor

### PR DESCRIPTION
**Pull request by gabru-md**
Added Anchor tag instead of Button and changed its position
as proposed in UI enhancement.

Fixes : https://github.com/fossasia/susi_chromebot/issues/66

Please review : @zamhaq @ms10398

### CODE REVIEW

**Comment by gabru-md** [comment]
ss

ScreenShot of the change

**Comment by zamhaq** [comment]
@gabru-md could you centre the SUSI logo ?

**Comment by gabru-md** [comment]
s1
Is this okay?

**Comment by zamhaq** [comment]
@gabru-md Yeah thats fine. I see that there is some dark box at the right bottom of `textarea`. Is that intended or that is something else ?

**Comment by gabru-md** [comment]
It is because of my linux mint theme. It is the part where you can hold and increase the box size. 
It is just because i have a `dark` theme installed. Nothing else

**Comment by zamhaq** [comment]
Ok then that's fine. There is no even spaces between the mic textbox and send. You can create a different issue and work on that if you want to otherwise just leave it open. I will merge this after a while.

**Comment by ms10398** [comment]
I am adding theme option i will change and commit it @zamhaq I am following Susi Light and Dark theme options.

**Comment by gabru-md** [comment]
@zamhaq Thanks!
Do merge it when you're free. :smiley:

**Pull request merged**
