### PR TITLE
fix issue  Settings icon in Dark theme

### PR DESCRIPTION
**Pull request by sachincool**
Fixes  https://github.com/fossasia/susi_chromebot/issues/114

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [ ] The unit tests pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

- [x] All the functions created/modified in this PR contain relevant docstrings.

#### Short description of what this resolves:
Adjusts the Settings icon with dark theme

#### Changes proposed in this pull request:

- fix issue  Settings icon in Dark theme

### CODE REVIEW

**Comment by zamhaq** [comment]
@sachincool please fix the conflicts

**Comment by sachincool** [comment]
done  @ms10398  @zamhaq  :+1:

**Comment by mariobehling** [comment]
Please resolve merge conflicts and work with the community to get more reviews. Cheers.

**Comment by zamhaq** [comment]
@sachincool please squash your commits. Thanks.

**Comment by sachincool** [comment]
closing this PR as rebasing the merge conflicts resulted in a whole new level of problems . 
I'll send a New PR  with 1 commit  RN 
Valuable lesson :- learnt that rebase doesnt  show  merge commits unless use `--preserved-merge` options

**Pull request closed without merging**
