### PR TITLE
Removed logout button and change password link

### LINKED ISSUE #333: Logout button on login screen
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/susi_server

**Current behavior:**
The logout button is present on the login page, which in my opinion should not be the case.

**Expected behavior:**
The logout button should be removed from this page and should be available only post login.

**Steps to reproduce:**
Open login.html in src folder of susi_chromebot

**Related Code**
```html
 <button class="btn btn-success" name="Logout" onClick="logout(this)" id="logout">Logout</button>
                        <br />
```

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by championballer**
Fixes #333 #334 #339 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [x] The unit tests pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

- [x] All the functions created/modified in this PR contain relevant docstrings.

#### Short description of what this resolves:
Removes logout button and change password link on login portal

#### Changes proposed in this pull request:

-Deleted the code related to the button 
-Deleted the code related to the link

bug

final

### CODE REVIEW

**Comment by zamhaq** [comment]
@championballer Can you mention the steps to reproduce the bug?

loginlogout

**Comment by championballer** [comment]
I just opened the login.html file in src folder and it was this way.

**Comment by zamhaq** [comment]
> I just opened the login.html file in src folder and it was this way.

This is the default markup that exists in the page. Depending on if certain conditions are fulfilled, some markup is displayed or hidden through Javascript in `login.js` file.

I hope it clears the issue? :smile: If you think this resolves your issue then please close this.

Thank You. :tada:

**Comment by championballer** [comment]
But what is the requirement of this markup in the first place? If any user sees this, then it should be an issue?

**Comment by zamhaq** [comment]
@championballer Yeah Sorry, have been out of the project for some time. It seems at first the code was operated in the as I mentioned above but now, the if user clicks on forgot password then he is taken to a new page. This is indeed redundant code. Thanks for finding this out :smile:

**Comment by championballer** [comment]
Oh. No issues. :smile:

**Comment by zamhaq** [comment]
> But what is the requirement of this markup in the first place? If any user sees this, then it should be an issue?

The problem here is that you are trying to access the login page directly instead of through the extension may be. Just try once through the extension if you are not doing that already?

**Comment by zamhaq** [comment]
> Oh. No issues.

Sorry for the previous comment again. That was again a misunderstanding on my part. This code is indeed required for the functionality of the extension.

**Comment by championballer** [comment]
Sure, let me look into it.

**Comment by zamhaq** [comment]
> Sure, let me look into it.

Have you created an issue for this one? If not please create one and if it's created then please mention the number on the Fixes line in your PR description. 

 Thanks.

**Pull request closed without merging**
