### PR TITLE
Added Travis CI

### PR DESCRIPTION
**Pull request by ms10398**
Added Travis CI

### CODE REVIEW

**Comment by ms10398** [comment]
Check Log Travis CI build is working as expected @gabru-md @zamhaq 
Now i have to improve all previous commits so that this PR can get merged
Working on it now will soon add a commit

**Comment by zamhaq** [comment]
@ms10398 I see you are using JSHINT. Can we use EsLint "airbnb style". What say? @gabru-md @ms10398

**Comment by ms10398** [comment]
We could but we are not using an jsx syntax in future if we switch to react or make any major change we can switch to eslint

**Comment by ms10398** [comment]
@zamhaq What do you suggest?
If you give a go i will fix all the errors and commit.

**Comment by zamhaq** [comment]
@ms10398 we can use it without react too. Later, extensions would be easy. But anyways, what do you think @gabru-md?

**Comment by gabru-md** [comment]
It looks good to me.
btw I am working on adduing more tests like for APIs assertion.
@zamhaq LGTM :rocket:

**Comment by zamhaq** [comment]
@gabru-md so JsHint or eslint 😄?

**Comment by gabru-md** [comment]
After studying about them i would suggest to go with JSHINT. As it has bug finding capabilities as well .
That's what i propose @zamhaq
So i am in favour of merging

**Comment by zamhaq** [comment]
@gabru-md well we could do that, anyways  hah! JSHint it is then.  @gabru-md tell me when you fix the commits

**Comment by ms10398** [comment]
I will be fixing the old commits by today

**Comment by gabru-md** [comment]
@ms10398 are you taking up this issue of fixing then ?
or should i ?

**Comment by ms10398** [comment]
I will be finishing it coz i already started after integrating Travis

**Pull request closed without merging**
