### PR TITLE
Open Chrome Extension to Left as window #344

### LINKED ISSUE #344: Open Chrome Extension to left as window
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/susi_server

**Current behavior:**
Not present

**Expected behavior:**
Add option to open the chrome extension to left as a window

**Other information:**
See the redux dev tool for reference.
screen shot 2018-09-23 at 1 50 50 pm

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by fragm3**
Fixes #344 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [x] The unit tests pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

- [x] All the functions created/modified in this PR contain relevant docstrings.

#### Short description of what this resolves:

Add option to open the chrome extension to left as a window

Screenshot:
screen shot 2018-09-27 at 1 37 13 am

#### Changes proposed in this pull request:

- Add context menu to load extension as a window to left

### CODE REVIEW

**Comment by fragm3** [comment]
@stealthanthrax does it needs to be approved? I cant see anyone approving issues.

**Comment by zamhaq** [comment]
@gabru-md @ms10398 thoughts?

**Comment by gabru-md** [comment]
I suppose this is another feature that we can give to the users of this application, we can go ahead with this @zamhaq , @fragm3 can you please solve the conflicts before we can provide any review on this PR ?

**Comment by fragm3** [comment]
@gabru-md resolved the conflicts. Thanks!

**Comment by mariobehling** [comment]
I am not sure neither. I think this feature is low priority and I am unsure that it should be integrated. Can we postpone this for now? Please close it for now. Thanks.

**Pull request closed without merging**
