### PR TITLE
Add gitter channel to README

### LINKED ISSUE #134: Add communication channel to readme
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/susi_server

**Current behavior:**
There is no information about the gitter communication channel.

**Expected behavior:**
Please add information about gitter channel to readme.md

### PR DESCRIPTION
**Pull request by gs0510**
Fixes #134 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `nextgen` branch.
- [x] The unit tests pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

- [x] All the functions created/modified in this PR contain relevant docstrings.

#### Short description of what this resolves:
Adds gitter channel to the README.

#### Changes proposed in this pull request:

-
-
-

### CODE REVIEW

**Comment by geekyd** [comment]
@gs0510 Thanks for the PR! It would be great if we follow a similar structure to the susi server. Please check https://github.com/fossasia/susi_server/blob/development/README.rst#communication

**Comment by ms10398** [comment]
@gs0510 Please squash the commits

**Comment by ms10398** [comment]
This can be closed @zamhaq

**Comment by zamhaq** [comment]
Closing this as `gitter` badge added.

**Pull request closed without merging**
