### PR TITLE
Clear Chat is working and fixed console errors

### LINKED ISSUE #448: Clear Chat is not working and fixing console error.s
**I'm submitting a ...**  (check one with "x")
- [x] bug report

**Current behavior:**

Clear chat option, not clearing chat.

**Expected behavior:**

Clear Chat option should clear the chat.

**Would you like to work on the issue?**

Please let us know if you can work on it or the issue should be assigned to someone else.
```
Yes

### PR DESCRIPTION
**Pull request by sk9331657**
Fixes #448 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [x] The unit tests pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

- [x] All the functions created/modified in this PR contain relevant docstrings.

### CODE REVIEW

**Comment by sk9331657** [comment]
@neeraj3029  Please merge.

**Comment by neeraj3029** [comment]
@sk9331657 I wish I could but I don't have merge access. 😅

**Comment by sk9331657** [comment]
@stealthanthrax Can you please merge this??

**Comment by sk9331657** [comment]
@prateekiiest  Can you please review and merge this??

**Pull request closed without merging**
