### PR TITLE
Fixes:#222 : Added Loading Feature and improved how the error is shown

### LINKED ISSUE #222: To add a loading feature in the login form
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/susi_server

**Current behavior:**
The login feature while loading gives no indication

**Expected behavior:**
To add a loader gif or a self-created pre-loader

**Would you like to work on the issue?**

**NO**

### PR DESCRIPTION
**Pull request by saikat041**
Fixes #222

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [x] The unit tests pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

- [ ] All the functions created/modified in this PR contain relevant docstrings.

#### Short description of what this resolves:
Added a loading  feature and improved how the error is shown.

#### Changes proposed in this pull request:

-
-
-

### CODE REVIEW

**Comment by saikat041** [comment]
@stealthanthrax  GIF of the changes given below:
susi login portal

**Comment by stealthanthrax** [comment]
@saikat041 , a screenshot of error screen would be appreciated

**Comment by stealthanthrax** [comment]
Also, @saikat041 ,the gif change shall not be accepted since the issue was assigned to @akshatnitd

**Comment by saikat041** [comment]
@stealthanthrax  This is how the error looks after my change.
screenshot 3

**Comment by akshatnitd** [comment]
@saikat041 Since, loading state was already handled in #245 , you can wait for it to merge and then modify the PR accordingly. Also, #222 was claimed by me, so you should have checked before starting, so that effort doesn't go in vain

**Pull request closed without merging**
