### PR TITLE
Add btn btn-danger class in logout button

### LINKED ISSUE #360: change color of the logout button
**Problem/Issue**
logout button has `success` green right now. It can be changed to like `warning` red or `error` yellow.

**Do you want to work on this?**
No

**Can this be claimed by anyone**
Yes

### PR DESCRIPTION
**Pull request by rupav**
Fixes #360 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [x] The unit tests pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

- [x] All the functions created/modified in this PR contain relevant docstrings.

#### Short description of what this resolves:
Instead of `btn-success` class, add `btn-danger` class to logout button.

#### Changes proposed in this pull request:

- I have added `btn-danger` class in logout button which makes it red in color. Refer:
image

- Other available options are:

image
image

### CODE REVIEW

**Comment by rupav** [comment]
@gabru-md @stealthanthrax @zamhaq @fragm3 which one looks the best?

**Comment by fragm3** [comment]
@rupav yellow i think

**Comment by ms10398** [comment]
I think red seems fine :+1:

**Comment by rupav** [comment]
@ms10398 will keep in mind from next time. 😀

**Pull request merged**
