### PR TITLE
add icon in the extension management page (chrome://extensions)

### LINKED ISSUE #92: Add different icon sizes in manifest.json
This is to ensure susi.ai icon'size on the toolbar is compatible with the platform used.
I had done similar type in fossasia/susi_firefoxbot [https://github.com/fossasia/susi_firefoxbot/pull/22](url) where I used an svg icon.
But Chrome does not show svg icon so will do something else.
Also, recommended sizes are:
[https://developer.chrome.com/apps/manifest/icons](url) .

**Would you like to work on it?**
Yes.

### PR DESCRIPTION
**Pull request by rupav**
Fixes #92 

#### Checklist

- [ x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [ x] My branch is up-to-date with the Upstream `nextgen` branch.
- [ ] The unit tests pass locally with my changes 
- [ x] I have added tests that prove my fix is effective or that my feature works
- [ x] I have added necessary documentation (if appropriate)

- [ x] All the functions created/modified in this PR contain relevant docstrings.

#### Short description of what this resolves:
PR rectified #94 

#### Changes proposed in this pull request:

- Refer #94 
Earlier

Change propsed:

### CODE REVIEW

**Comment by rupav** [comment]
@gabru-md  @ms10398 , Its now ready to be merged :)

**Comment by rupav** [comment]
@zamhaq Please review it.

**Comment by gabru-md** [comment]
@zamhaq please squash and merge them.

**Comment by rupav** [comment]
@gabru-md  I have squashed m commits. 
@zamhaq it updates the readme too :).

**Pull request merged**
