### PR TITLE
Added UP/DOWN key Event

### PR DESCRIPTION
**Pull request by gabru-md**
Pressing Up/Down keys copies the previous/next message into the text area.

Fixes : https://github.com/fossasia/susi_chromebot/issues/83

### CODE REVIEW

**Comment by gabru-md** [comment]
@ms10398 @zamhaq Please Review :)

**Comment by gabru-md** [comment]
@zamhaq merge this ?

**Comment by zamhaq** [comment]
@gabru-md one more review is pending I guess.

**Comment by gabru-md** [comment]
Thanks!

**Pull request merged**
