### PR TITLE
Fixed Image Display

### PR DESCRIPTION
**Pull request by ms10398**
Fixed https://github.com/fossasia/susi_chromebot/issues/22

Screenshots are attached below

screenshot from 2017-09-25 03-18-18

screenshot from 2017-09-25 03-18-39

@gabru-md @zamhaq Please review
I have tried to tackle all edge cases review and check if this works well.

### CODE REVIEW

**Comment by gabru-md** [comment]
@ms10398 
Does it not show text now ? Please add a  complete screenshot.

**Comment by ms10398** [comment]
It shows the text too.

Screenshot with text-
screenshot from 2017-09-25 11-04-11

But i will recommend to test it too so that no cases are left which are not covered by my approach.
Thanks

**Comment by zamhaq** [comment]
@gabru-md Please review. LGTM with the screenshots provided.

**Comment by gabru-md** [comment]
@ms10398 we can always work upon the left over cases. Rest lgtm.

**Pull request merged**
