### PR TITLE
Adds Map type response to SUSI Chromebot

### PR DESCRIPTION
**Pull request by gabru-md**
This PR adds Map type response to SUSI Chromebot. This has been done
using leafletJS

Closes https://github.com/fossasia/susi_chromebot/issues/157

Fixes #

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [ ] My branch is up-to-date with the Upstream `master` branch.
- [ ] The unit tests pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

- [ ] All the functions created/modified in this PR contain relevant docstrings.

#### Short description of what this resolves:
Adds Map type response to SUSI Chromebot

Cheers!

### CODE REVIEW

**Comment by gabru-md** [comment]
@ms10398 Please let me know how do i pass travis?
It says `L` not defined but it is because of the fact that `L` is derived from `leaflet.js` and hence will not be present in `script.js`

**Comment by gabru-md** [comment]
@ms10398 Please see the GIF here : https://imgur.com/a/vlR2u
Due to some reason Github was not uploading my GIF here so I had to upload it on `imgur`.
Thanks!

**Comment by gabru-md** [comment]
@stealthanthrax review?

**Comment by gabru-md** [comment]
@zamhaq please review

**Comment by ms10398** [comment]
I think you have not pulled his latest changes @stealthanthrax

**Comment by gabru-md** [comment]
It is an anchor type response. I will create an issue and start working on it asap. Thanks for pointing out.

**Comment by gabru-md** [comment]
It is a seperate thing to work upon and is not related to map type response. 
Therefore I have created a new issue and will provide a PR in a day or two.

**Comment by gabru-md** [comment]
@zamhaq  @stealthanthrax  review please so that it can be merged

**Comment by zamhaq** [comment]
@gabru-md anything wrong with my query? `where is Bangalore?`. Getting `sorry request could not be made.`

**Comment by gabru-md** [comment]
That is a network error.
I guess api.susi.ai is hosted on Cloudflare so it sometimes sends 403 server error and all you need to do is open up api.susi.ai and it will ask you if you are a robot or not. just pass the captcha and retry the query.

Happened with me as well :laughing:

**Comment by gabru-md** [comment]
ping @zamhaq

**Comment by zamhaq** [comment]
@gabru-md on it. Let me try your way once, otherwise, it has been tested by @ms10398 right?

**Comment by gabru-md** [comment]
Yes, It is! I also have a GIF provided for reference as well @zamhaq

**Comment by ms10398** [comment]
Yes I had tested it 
Map response worked perfect but then anchor response was not supported so gabru is working on it now

**Comment by gabru-md** [comment]
Welcome @zamhaq
Merge possible?

**Pull request merged**
