### PR TITLE
Fixed the alert bug on OSX that was causing the extension to quit

### LINKED ISSUE #282: Chromebot closes on clicking mic icon
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/susi_server

**Current behavior:**
Chromebot closes by clicking on mic icon

**Expected behavior:**
To display warning in some other way

**Steps to reproduce:**
open cbot and click on the mic icon

Your operating system
OSX

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by stealthanthrax**
Fixes #282 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [x] The unit tests pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

- [x] All the functions created/modified in this PR contain relevant docstrings.

#### Short description of what this resolves:
This fixes the bug that used to close the chromebot on clicking the mic 

#### Changes proposed in this pull request:

Used a different a jquery plugin to make alert notifications

### CODE REVIEW

**Comment by stealthanthrax** [comment]
@ms10398 , it was used by mistake , have a look now

**Comment by stealthanthrax** [comment]
before 
before
after
after

**Comment by stealthanthrax** [comment]
@ms10398 ,could you have a look again?

**Comment by stealthanthrax** [comment]
@gabru-md @zamhaq @ms10398

**Comment by gabru-md** [comment]
@stealthanthrax don't you think that having different alert types for different OS would be a bit tedious?
How about having the very same type of alert that you have here for OS-X, for every other OS?
@ms10398

**Comment by gabru-md** [comment]
Sorry, I didn't see that you have already done it for all.
Thanks!

**Comment by ms10398** [comment]
@gabru-md Should we merge as you were working on splitting files?

**Comment by gabru-md** [comment]
@ms10398 Splitting the files is taking a lot of time since I have to figure out all the dependent functions, and then split them.
You can merge this. I will be working on it in the meanwhile.

**Pull request merged**
