### PR TITLE
read correct response and support table type response

### LINKED ISSUE #80: Wrong response read from server
**actual behaviour**
Currently, the `answers[0].data[0]` field is being read. This is not the correct response to read. Wrongly, the request is being send twice from the client side.
image

**Expected behaviour**
Send the request only once for one query. Read the correct response which is the `actions` attribute.
**Please refer to the API doc at** https://dev.susi.ai/skills/susi_chat_api.html

**Would you like to work on this ?**
No

### PR DESCRIPTION
**Pull request by zamhaq**
Fixes #80 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `nextgen` branch.
- [ ] The unit tests pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

- [ ] All the functions created/modified in this PR contain relevant docstrings.

#### Changes proposed in this pull request:

- Read correct response
- Support table type response
- Update .jshintrc and Gruntfile.js to support es6 syntax

### CODE REVIEW

**Comment by zamhaq** [comment]
@gabru-md please review.

**Comment by zamhaq** [comment]
@gabru-md No problem. @ms10398 I think web search is not working now. Try this:- https://api.susi.ai/susi/chat.json?q=fossasia. It gives 500 error. Therefore, I could not make a response type for web search and rss type. Once it starts giving valid response you can implement those type of responses. Please test the URL if it gives `500` error?

**Comment by ms10398** [comment]
Yeah I checked that I would like to work on it as soon as the server sends the correct response!
And I really like the effort you have put in to make it perfect

**Comment by ms10398** [comment]
There is a merge conflict @zamhaq Please resolve it

**Comment by gabru-md** [comment]
@ms10398 great! 
My treatment will be over by this week, so maybe I'll resume finding and fixing the bugs as well.

**Comment by ms10398** [comment]
Thats great @gabru-md I will love to work together and make extension a great success!

**Pull request merged**
