### PR TITLE
Added descriptive logos to nav bar

### PR DESCRIPTION
**Pull request by stealthanthrax**
susi

 I have read the Contribution & Best practices Guide and my PR follows them.
 My branch is up-to-date with the Upstream nextgen branch.
 The unit tests pass locally with my changes
 I have added tests that prove my fix is effective or that my feature works
 I have added necessary documentation (if appropriate)
 All the functions created/modified in this PR contain relevant docstrings.
Short description of what this resolves:

UI update

Changes proposed in this pull request:

Added descriptive logos in the susi-navbar

### CODE REVIEW

**Comment by stealthanthrax** [comment]
@ms10398, I am unable to think of any logo that goes with clear chat button and also matches the susi theme,Could you please suggest something?And for the padding , I'll do it.

**Comment by ms10398** [comment]
I have messaged you @stealthanthrax on gitter

**Comment by stealthanthrax** [comment]
@ms10398 , I have updated and squashed the commits and also have implemented your suggestions.
Please have a look 😄

**Comment by zamhaq** [comment]
@stealthanthrax please resolve the conflicts.

**Comment by stealthanthrax** [comment]
@ms10398 @zamhaq ,please have a look 😄

**Comment by ms10398** [comment]
Please squash commits @stealthanthrax

**Comment by stealthanthrax** [comment]
So,I am having trouble in squashing and merging .So,I will creating a new PR.

**Comment by zamhaq** [comment]
@stealthanthrax you have replaced many `PR` like this, go ahead but try to learn how to have an effective workflow so that you don't have to deal with these kind of problems all the time. I had the same problem earlier. You can ping me some time if you have trouble figuring it out.  ☺️

**Comment by ms10398** [comment]
This PR can now be closed @zamhaq

**Pull request closed without merging**
