### PR TITLE
issue#26 fixes: missing file added 

### PR DESCRIPTION
**Pull request by AshishkrGoyal**
@zamhaq  sir..
please review this PR..

Thanks In Advance 😄

### CODE REVIEW

**Comment by gabru-md** [comment]
@AshishkrGoyal since this corresponds to just one issue therfore please squash your commits. 
Btw Thanks for your contribution .
Cheers

**Comment by AshishkrGoyal** [comment]
@gabru-md it means that is is not good that i have added **description** in **manifest.json** ??
if i am right then please let me know...
Thanks 👍

**Comment by gabru-md** [comment]
Its very good that you fixed two things.
But try to make it as one commit. 
Squashing means putting all your work under a single commit. 
Please note : I'm not discouraging your work
It is highly thankful
Cheers.

**Comment by AshishkrGoyal** [comment]
@gabru-md sir..
i will keep it mind next time, thanks for telling this :smile: 
Thanks :+1:

**Comment by gabru-md** [comment]
We are on the same level in this community
So no need to call anyone 'sir'
Cheers

**Pull request merged**
