### PR TITLE
Fix Uneven spaces and Color of Susi messages in dark mode

### PR DESCRIPTION
**Pull request by ms10398**
Fixes https://github.com/fossasia/susi_chromebot/issues/72 https://github.com/fossasia/susi_chromebot/issues/81

There are two commits in the PR as it fixes two different issues.

#### Checklist

- [X] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [X] My branch is up-to-date with the Upstream `nextgen` branch.
- [ ] The unit tests pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] All the functions created/modified in this PR contain relevant docstrings.

#### Screenshots of the change

screenshot from 2017-09-30 10-25-27

screenshot from 2017-09-30 10-25-37

@zamhaq @gabru-md Please review

### CODE REVIEW

**Comment by gabru-md** [comment]
@ms10398 It seems that your change of `width` to `118%` is not working at my end.

**Comment by ms10398** [comment]
Can you post a screenshot @gabru-md

**Comment by gabru-md** [comment]
asd

Here it is

**Comment by ms10398** [comment]
Have you updated the fork @gabru-md

**Comment by gabru-md** [comment]
I cloned the fossasia's repository for testing purpose, although i may have to update my fork as well.
But it is caused by the 118% width .
Can you tell me if anything can be done of it ?

**Comment by ms10398** [comment]
I checked on two PC's now but it works I dont know why it doesn't works in your case.

**Comment by gabru-md** [comment]
Okay! Let me see.
Can it be because of the Monitor/Laptop Screen size as well?

**Comment by ms10398** [comment]
Yes sure!

**Pull request merged**
