### PR TITLE
updated signup.html

### LINKED ISSUE #353: Label Should be changed in confirm Password
**I'm submitting a ...**  (check one with "x")
- [X] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/susi_server

**Current behavior:**

screenshot - 9_24_2018 12_31_09 am

**Expected behavior:**

screenshot - 9_24_2018 12_32_31 am

**Steps to reproduce:**

Go to signup page .

**Would you like to work on the issue?**

Please let us know if you can work on it or the issue should be assigned to someone else.

 Yes

### PR DESCRIPTION
**Pull request by leoking-crey**
updated the value of label for confim password

Fixes #353 

#### Checklist

- [x ] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x ] My branch is up-to-date with the Upstream `master` branch.
- [x ] The unit tests pass locally with my changes 
- [ x] I have added tests that prove my fix is effective or that my feature works
- [x ] I have added necessary documentation (if appropriate)

#### Short description of what this resolves:
Changes the label for the confirm password field

### CODE REVIEW

**Comment by rupav** [comment]
Please change PR description to something like `Changed label of Confirm Password input field`. Be more specific with the description. Rest looks fine 👍

**Comment by gabru-md** [comment]
@leoking-crey please update the commit message so I can merge, maybe?

**Comment by gabru-md** [comment]
@leoking-crey please resolve the conflicts so that we can merge this?
cheers!

**Comment by mariobehling** [comment]
Please resolve conflicts

**Comment by gabru-md** [comment]
Closing this PR as no update is being applied to it.
Please reopen it in case you update it. Thank you :)

**Pull request closed without merging**
