### PR TITLE
Cleans up Repository and added GIF 

### PR DESCRIPTION
**Pull request by gabru-md**
Extension Related files into `src` folder
Added gif and readme updated
and Contributing.md added

Closes : https://github.com/fossasia/susi_chromebot/issues/45

### CODE REVIEW

**Comment by gabru-md** [comment]
@zamhaq @ms10398 Please Review

**Comment by zamhaq** [comment]
@gabru-md @ms10398 I am going ahead with the merge.

**Comment by gabru-md** [comment]
sure @zamhaq

**Comment by zamhaq** [comment]
@gabru-md @ms10398  any other PR please wait until tomorrow. I will try to merge them by tonight if possible but I have some exams so might not be able. Thanks.

**Comment by gabru-md** [comment]
@zamhaq No problem.
All the best for your exam.
Cheers!

**Comment by ms10398** [comment]
Yes sure all the best for your exams

**Comment by ms10398** [comment]
Great Work!! @gabru-md with the PR!! Cheers!

**Comment by gabru-md** [comment]
Thank You @ms10398 :blush:

**Pull request merged**
