### PR TITLE
Susi style side menu and side menu button added

### PR DESCRIPTION
**Pull request by stealthanthrax**
changes

### CODE REVIEW

**Comment by zamhaq** [comment]
Squash the commits @stealthanthrax

**Comment by stealthanthrax** [comment]
@zamhaq please check

**Comment by stealthanthrax** [comment]
@ms10398 @gabru-md

**Comment by zamhaq** [comment]
@stealthanthrax resolve the merge conflicts.

**Comment by ms10398** [comment]
Resolve the merge conflicts @stealthanthrax

**Comment by ms10398** [comment]
Please squash your commits @stealthanthrax

**Comment by ms10398** [comment]
@zamhaq @gabru-md Please have a look

**Comment by zamhaq** [comment]
@stealthanthrax This is how it appears on my browser:- 

sidemenu

Also, mention the issue you are fixing in your **PR** and the `settings` link which should lead to `options.html` is also not working. Please fix this issues. Thanks.

**Comment by stealthanthrax** [comment]
@zamhaq now check please

**Comment by tabesin** [comment]
"Working functionality" does not relate to this ticket afaik see.

**Comment by stealthanthrax** [comment]
@tabesin I can't understand what your statement means

**Comment by tabesin** [comment]
"Susi style side menu and side menu button added" means adding the menu, not adding a menu where functionality is fully working.

**Comment by ms10398** [comment]
Please solve the merge conflicts @stealthanthrax

**Pull request closed without merging**
