### PR TITLE
Table Response Responsive

### PR DESCRIPTION
**Pull request by ms10398**
Fixes https://github.com/fossasia/susi_chromebot/issues/112
#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [x] The unit tests pass locally with my changes
- [x] I have added necessary documentation (if appropriate)

#### Short description of what this resolves:
Table Response is now visible in a seperate message box which has a scrollbar

#### Changes proposed in this pull request:

- Table Response has a seperate scrollbar.

### CODE REVIEW

**Comment by ms10398** [comment]
Yes sorry I should have gone with a modular approach and made a function for it
I will try to follow code standards in the future.

**Comment by zamhaq** [comment]
@ms10398 can you remove the scrollbar inside the table that you display since there is already one scrollbar for the message box and two scrollbars does not look good. :+1:

**Comment by ms10398** [comment]
okay @zamhaq will do so

**Comment by ms10398** [comment]
@zamhaq did as you said check now if its okay.

**Pull request merged**
