### PR TITLE
#128 #129 #127 #130 UI issues fixed

### LINKED ISSUE #128: Set text area resizeable to false
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/susi_server

**Current behavior:**

Text area to input message can be resized which is a very bad ui

**Expected behavior:**

It should not be resizable by user and overflow should be allowed in case of text overflows

**Steps to reproduce:**

Click on extend icon on lower right corner of message text area and extend to bottom

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by VRamazing**
Fixes #128 and #129 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `nextgen` branch.
- [x] The unit tests pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

- [x] All the functions created/modified in this PR contain relevant docstrings.

#### Short description of what this resolves:
1)Improves footer layout.Adds right margin to send button and increases width of text area
2)Make text area resizable to none

### CODE REVIEW

**Comment by zamhaq** [comment]
@VRamazing please add screenshots for UI fix.

**Comment by VRamazing** [comment]
@zamhaq updated.

**Comment by VRamazing** [comment]
@zamhaq  ok

**Comment by zamhaq** [comment]
@VRamazing It would better if you tackle #130 in this `PR` itself since that's a small change(I suppose?) and all the issues are related.

**Comment by VRamazing** [comment]
@zamhaq I was about to ask that question :smiley:

**Comment by VRamazing** [comment]
susi
Looks good to me.Let me know if you want changes @zamhaq

**Comment by zamhaq** [comment]
As you can see the `send` icon is overlapping the text area. Please fix that @VRamazing. Thanks.

**Comment by VRamazing** [comment]
@zamhaq How is this possible.Are you sure you are using my build.It seems to be running great in my browser even on resizing.

**Comment by zamhaq** [comment]
@ms10398 @gabru-md please review.

**Comment by ms10398** [comment]
It shows the same way as @zamhaq said in my laptop too check again.

**Comment by ms10398** [comment]
@VRamazing Whats the progress on it

**Comment by VRamazing** [comment]
@ms10398  I am sorry I can't seem to recreate the issue.The code seems to run fine on my laptop.I have even tried it on my PC and it works fine.Really confused on how to fix this.

**Comment by VRamazing** [comment]
@zamhaq @ms10398  I have made some changes.Please check.

**Comment by zamhaq** [comment]
@VRamazing :+1: please squash your commits.

**Comment by VRamazing** [comment]
@zamhaq Please check

**Comment by zamhaq** [comment]
@VRamazing please squash commits.

**Comment by VRamazing** [comment]
@zamhaq done.

**Comment by VRamazing** [comment]
@zamhaq  I don't think there will be any other issue.Base conflicts have also been resolved.All that is left to do is merge.Hopefully this will be the end of it.

**Comment by ms10398** [comment]
Please resolve the conflicts @VRamazing

**Comment by VRamazing** [comment]
This has been the worst experience so far

**Comment by gabru-md** [comment]
Dont get exhausted @VRamazing.
Everybody goes through this phase once as a developer.
Cheers!

**Comment by ms10398** [comment]
Please Squash the commits also @VRamazing

**Comment by VRamazing** [comment]
@gabru-md  I am not exhausted.I am frustrated. I resolved all conflicts and merged and squashed the commits yesterday.I am checking this morning and new conflict have arisen. It was not even necessary to assign it to me.The conflicts were pretty simple and could have easily been resolved by anyone with write access when merging to base branch.It would have taken hardly 5 minutes if anyone would have checked.Its pathetic to be stuck at the same thing. I need to move on.

**Comment by VRamazing** [comment]
@ms10398 Any change I have made have already been squashed and I don't think its prudent to squash the changes that others have made into my commit.You can squash it while merging if you think otherwise.

**Comment by zamhaq** [comment]
@VRamazing sorry that you had to do the same task over again, but until you resolve the conflicts and squash your commits I cannot merge your PR. According to fossasia best practices a PR needs to have two approved reviews and then the 3rd reviewer or any one with write access can merge that PR. Yes the maintainer could have squashed and merged but it would take more of his time, hence it is in the best practice to write meaningful commit messages and squash commits. Since this is a very small projects and the main file is not split up into many components,  conflicts arise frequently. Sorry you had to go through this and thanks for your contribution.

**Comment by zamhaq** [comment]
@ms10398 @gabru-md please review and approve if everything is fine.

**Pull request merged**
