### PR TITLE
Now the submit button matches the susi theme

### PR DESCRIPTION
**Pull request by stealthanthrax**

### CODE REVIEW

**Comment by zamhaq** [comment]
@stealthanthrax the travis checks are failing. Plus, when you change something in UI please provide the screenshot, also read the [contributing.md](https://github.com/fossasia/susi_chromebot/blob/master/CONTRIBUTING.md). Thanks.

**Comment by gabru-md** [comment]
@zamhaq there is nothing wrong with this PR ,
Travis is failing due to a `ruby` command-> `rake`
Although the `.travis.yml` is configured according to `nodejs` , there seems to be some problem with it.
So there is nothing wrong with this PR. I assure you you can merge it.

**Comment by zamhaq** [comment]
@gabru-md ok Thanks. But still the remaining issues still exist (screenshot and which issue it is fixing).

**Comment by gabru-md** [comment]
Yes! I agree
@stealthanthrax Please add relevant screenshots to prove your PR. 
Thanks for the contribution anyway.

**Comment by gabru-md** [comment]
Yes! I agree
@stealthanthrax Please add relevant screenshot to prove your PR.
Thanks.

**Comment by ms10398** [comment]
This PR was made before Travis was configured thats why Travis is failing. @gabru-md @zamhaq 
Yes @stealthanthrax  UI improvements must be accompanied by a screenshot.

**Comment by gabru-md** [comment]
@ms10398 Thanks!
I just found that out by `google-ing` it too.
@stealthanthrax Please update your branch after this PR so that none of your future commits fail the build.
Thanks!

**Comment by stealthanthrax** [comment]
@zamhaq @gabru-md @ms10398 Sorry for not accompanying the pr with screenshot.
Also,if anyone can help me with travis checks , i would really appreciate it.

**Comment by gabru-md** [comment]
You can do so by updating your fork with the upstream/master.
This will solve your travis problem.

**Comment by ms10398** [comment]
Just as @gabru-md said you just need to update your fork with upstream/master.

**Comment by zamhaq** [comment]
@stealthanthrax will you update this `PR` ? or shall I close this ?

**Comment by stealthanthrax** [comment]
@zamhaq @gabru-md  @ms10398   i have created a new Pr #76 for the same issue.If you could review it pease.

**Pull request closed without merging**
